### ISSUE TITLE
To-do LIST

### ISSUE THREAD

**Issue by randomCoolProjects** [randomCoolProjects/AgemChat#1]
- [x] **VERSÃO 1.5:**

  - [x] Esconder data e horário de envio das mensagens - Mostrar apenas quando passar o cursor em cima

  - [x] Privilégios de administrador

  - [x] Banir usuários

  - [x] Resolver bug do timeout

  - [x] Melhorar UI de login

  - [x] Recursos de segurança - prevenir ataques XSS (client-side) -- somente o admin pode enviar HTML

- [x] **VERSÃO 1.9:**

  - [x] Novo nome para o APP/Chat

  - [x] Sistema para possibilitar mais de um administrador

  - [x] Possibilitar instalação de temas

  - [x] Masterchat Marketplace

  - [x] ~~Permitir envio de arquivos~~ e leve formatação de texto -- HTML automático

  - [x] Notificar quando chegar uma atualização

  - [x] Divulgação/Marketing

  - [x] Sistema "lite" - cache de scripts, html e css usando localStorage 
 
- [x] **VERSÃO 1.9.1** (XMLHttpRequestSíncrono é obsoleto)

   - [x] Usar XMLHttpRequest assíncrono

- [ ] **VERSÃO 2.0**

   - [x] Sistema de sala privada com usuários

   - [ ] Página para entrar/sair de grupos

   - [ ] Possibilitar envio de áudios e arquivos

   - [x] Cache de mensagens / receber uma por vez

   - [ ] Notificações 

   - [x] Novo formato de mensagens

- [ ] **VERSÃO 2.1**

   - [ ] Segurança

   - [ ] Bug fix

   - [ ] Refatoração
